### PR TITLE
Errors2

### PR DESCRIPTION
**Pull request by josepjaume**
Hi! I've put your branch up-to-date with the latest ember.js and ember-data changes. Needs some squashing :)

Keep on the good work! This feature is really amazing and non-trivial.

### CODE REVIEW

**Comment by josepjaume** [comment]
Also, I have a doubt with how to use transactions and handle invalid states.

``` Javascript
var transaction = App.store.transaction(),
    record = transaction.createRecord(App.Contact);

record.set('name', '');
transaction.commit();
// Commit fails with a 422 and populates correctly the errors object

record.set({name: 'Chuck Norris'});
transaction.commit();
// Doesn't try to send the record to the store again
```

**Comment by josepjaume** [comment]
Ok, I detected the source of the problem: Re-commiting does work, but only within the default transaction. I thought I had fixed it with this commit but doesn't seem so.

**Comment by josepjaume** [comment]
When I say "within the default transaction" I mean if I use `App.store.createRecord(App.Contact)` and `App.store.commit()`. In this case it gets commited each time I intend to do so.

I also found out this behavior actually occurs in the current codebase if I modify the rest adapter so `422` responses trigger a `record.send('becameInvalid', errors)` - so probably this is an issue within ember-data itself.

Do you have any clue why does that happen?

**Comment by tchak** [comment]
@josepjaume this is intentional for now. After each commit a transaction is discarded and all non committed records are added back to the default transaction.
I think we should allow to call transaction.add on dirty records so you can change transaction before recommitting.

As for this commit, it sims like it will not go in data as is. I talked with @tomdale a little bit about it and he simed to want something more advanced with different classes of errors and stuff. He also wanted to make a better separation between errors / sever validation / client validation

**Comment by josepjaume** [comment]
Yes, I totally get the point of having a really complete error handling, since it's something not trivial and that hugely impacts user experience.

Regarding re-adding a dirty record to a transaction, that could be a solution. But I don't kinda get the conceptual implications of why is it getting discarded on the first place - not discarding it would be even better.

Without having this figured out, invalid states are not that useful, at least within transactions. I'm being able to do this on the default transaction, but it's always possible that someplace I'm commiting for some reason and sending a dirty record by mistake.

How are you handling this scenarios in your applications?

Thanks for the explanations and have a good day!

**Pull request closed without merging**
